# Generated by Django 3.1 on 2021-04-11 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20210411_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tour.player'),
        ),
    ]
