# Generated by Django 3.1 on 2021-04-13 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20210411_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_booked',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tour.player'),
        ),
        migrations.DeleteModel(
            name='cards',
        ),
    ]
