# Generated by Django 3.1 on 2021-04-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_auto_20210413_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_booked',
            name='sent_off',
            field=models.CharField(default='y', max_length=1),
            preserve_default=False,
        ),
    ]
