# Generated by Django 3.1 on 2021-04-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_player_booked_sent_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team_id',
        ),
        migrations.AddField(
            model_name='player',
            name='team_id',
            field=models.ManyToManyField(related_name='players', to='tour.kfupm_team'),
        ),
    ]
