# Generated by Django 3.1 on 2021-04-24 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_auto_20210424_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team_id',
        ),
        migrations.AddField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tour.kfupm_team'),
            preserve_default=False,
        ),
    ]
